function [R1Ax,R1Ay,R1Az,R1Bx,R1By,R1Bz,R1Hx,R1Hy,R1Hz,R1Energy] = ...
    PlotRegion(...
        InterpDiv,...
        RegionMu,...
        Volume,...
        MVP,...
        RegionElements,...
        EdgeNodesTable,...
        GlobalNodeNumbering)

NumRegionElements = length(RegionElements(:,1));
InterpSpacing = 2/InterpDiv;    % This is divided by two because the 
                                % parametric domain is from -1 to 1

StorSize = floor(2/InterpSpacing)+1;    % Storage size for all fields

R1Ax = zeros(StorSize,StorSize,StorSize,NumRegionElements);
R1Ay = zeros(StorSize,StorSize,StorSize,NumRegionElements);
R1Az = zeros(StorSize,StorSize,StorSize,NumRegionElements);
R1Bx = zeros(StorSize,StorSize,StorSize,NumRegionElements);
R1By = zeros(StorSize,StorSize,StorSize,NumRegionElements);
R1Bz = zeros(StorSize,StorSize,StorSize,NumRegionElements);
R1Hx = zeros(StorSize,StorSize,StorSize,NumRegionElements);
R1Hy = zeros(StorSize,StorSize,StorSize,NumRegionElements);
R1Hz = zeros(StorSize,StorSize,StorSize,NumRegionElements);
R1Energy = zeros(NumRegionElements,1);

% Solve for all values, then plot all values
for el = 1:NumRegionElements
    Edges = RegionElements(el,:);
    [Bx,By,Bz,Ax,Ay,Az,~,~,~,~,~,~] = ...
        PlotEdgeProcessing(MVP(Edges),InterpSpacing);
    R1Ax(:,:,:,el) = Ax;
    R1Ay(:,:,:,el) = Ay;
    R1Az(:,:,:,el) = Az;
    R1Bx(:,:,:,el) = Bx;
    R1By(:,:,:,el) = By;
    R1Bz(:,:,:,el) = Bz;
    Hx = RegionMu*Bx;
    Hy = RegionMu*By;
    Hz = RegionMu*Bz;
    R1Hx(:,:,:,el) = Hx;
    R1Hy(:,:,:,el) = Hy;
    R1Hz(:,:,:,el) = Hz;
    R1Energy(el,1) = 1/2*Volume*sum(sum(sum(Bx.*Hx+By.*Hy+Bz.*Hz)));
end

% Plot Magnetic Vector Potential
%{
hold on;
for el = 1:NumRegionElements
    ElementEdgeNodesXYZ = GetElementEdgeNodesXYZ(el,...     
        Region2Elements,...
        EdgeNodesTable,...
        GlobalNodeNumbering);
    MaxCoord = ...
        max([ElementEdgeNodesXYZ(:,1:3);ElementEdgeNodesXYZ(:,4:6)]);
    MinCoord = ...
        min([ElementEdgeNodesXYZ(:,1:3);ElementEdgeNodesXYZ(:,4:6)]);
    LocalXInterp = ...
        MinCoord(1):abs(MaxCoord(1)-MinCoord(1))/InterpDiv:MaxCoord(1);
    LocalYInterp = ...
        MinCoord(2):abs(MaxCoord(2)-MinCoord(2))/InterpDiv:MaxCoord(2);
    LocalZInterp = ...
        MinCoord(3):abs(MaxCoord(3)-MinCoord(3))/InterpDiv:MaxCoord(3);
    [XInterp,YInterp,ZInterp] = ...
        meshgrid(LocalXInterp,LocalYInterp,LocalZInterp);
    quiver3(XInterp,YInterp,ZInterp,...
        R1Ax(:,:,:,el),R1Ay(:,:,:,el),R1Az(:,:,:,el),'b');
end
%}
PlotEdgeField(NumRegionElements,RegionElements,EdgeNodesTable,...
    GlobalNodeNumbering,InterpDiv,...
    R1Ax,R1Ay,R1Az,...
    'm',...
    'Magnetic Vector Potential',...
    'A');

% Plot Magnetic Flux
%{
hold on;
for el = 1:NumRegionElements
    ElementEdgeNodesXYZ = GetElementEdgeNodesXYZ(el,...     
        Region2Elements,...
        EdgeNodesTable,...
        GlobalNodeNumbering);
    MaxCoord = ...
        max([ElementEdgeNodesXYZ(:,1:3);ElementEdgeNodesXYZ(:,4:6)]);
    MinCoord = ...
        min([ElementEdgeNodesXYZ(:,1:3);ElementEdgeNodesXYZ(:,4:6)]);
    LocalXInterp = ...
        MinCoord(1):abs(MaxCoord(1)-MinCoord(1))/InterpDiv:MaxCoord(1);
    LocalYInterp = ...
        MinCoord(2):abs(MaxCoord(2)-MinCoord(2))/InterpDiv:MaxCoord(2);
    LocalZInterp = ...
        MinCoord(3):abs(MaxCoord(3)-MinCoord(3))/InterpDiv:MaxCoord(3);
    [XInterp,YInterp,ZInterp] = ...
        meshgrid(LocalXInterp,LocalYInterp,LocalZInterp);
    quiver3(XInterp,YInterp,ZInterp,...
        R1Bx(:,:,:,el),R1By(:,:,:,el),R1Bz(:,:,:,el),'b');
end
%}
PlotEdgeField(NumRegionElements,RegionElements,EdgeNodesTable,...
    GlobalNodeNumbering,InterpDiv,...
    R1Bx,R1By,R1Bz,...
    'm',...
    'Magnetic Flux',...
    'B');

% Plot Magnetic Field Intensity
%{
hold on;
for el = 1:NumRegionElements
    ElementEdgeNodesXYZ = GetElementEdgeNodesXYZ(el,...     
        Region2Elements,...
        EdgeNodesTable,...
        GlobalNodeNumbering);
    MaxCoord = ...
        max([ElementEdgeNodesXYZ(:,1:3);ElementEdgeNodesXYZ(:,4:6)]);
    MinCoord = ...
        min([ElementEdgeNodesXYZ(:,1:3);ElementEdgeNodesXYZ(:,4:6)]);
    LocalXInterp = ...
        MinCoord(1):abs(MaxCoord(1)-MinCoord(1))/InterpDiv:MaxCoord(1);
    LocalYInterp = ...
        MinCoord(2):abs(MaxCoord(2)-MinCoord(2))/InterpDiv:MaxCoord(2);
    LocalZInterp = ...
        MinCoord(3):abs(MaxCoord(3)-MinCoord(3))/InterpDiv:MaxCoord(3);
    [XInterp,YInterp,ZInterp] = ...
        meshgrid(LocalXInterp,LocalYInterp,LocalZInterp);
    quiver3(XInterp,YInterp,ZInterp,...
        R1Hx(:,:,:,el),R1Hy(:,:,:,el),R1Hz(:,:,:,el),'b');
end
%}
PlotEdgeField(NumRegionElements,RegionElements,EdgeNodesTable,...
    GlobalNodeNumbering,InterpDiv,...
    R1Hx,R1Hy,R1Hz,...
    'm',...
    'Magnetic Field Intensity',...
    'H');