function PlotEdgeField(...
    NumRegionElements,...
    RegionElements,...
    EdgeNodesTable,...
    GlobalNodeNumbering,...
    InterpDiv,...
    RValX,RValY,RValZ,...
    LengthUnit,...
    FieldName,...
    FieldVariable)

hold on;
for el = 1:NumRegionElements
    ElementEdgeNodesXYZ = GetElementEdgeNodesXYZ(el,...     
        RegionElements,...
        EdgeNodesTable,...
        GlobalNodeNumbering);
    MaxCoord = ...
        max([ElementEdgeNodesXYZ(:,1:3);ElementEdgeNodesXYZ(:,4:6)]);
    MinCoord = ...
        min([ElementEdgeNodesXYZ(:,1:3);ElementEdgeNodesXYZ(:,4:6)]);
    LocalXInterp = ...
        MinCoord(1):abs(MaxCoord(1)-MinCoord(1))/InterpDiv:MaxCoord(1);
    LocalYInterp = ...
        MinCoord(2):abs(MaxCoord(2)-MinCoord(2))/InterpDiv:MaxCoord(2);
    LocalZInterp = ...
        MinCoord(3):abs(MaxCoord(3)-MinCoord(3))/InterpDiv:MaxCoord(3);
    [XInterp,YInterp,ZInterp] = ...
        meshgrid(LocalXInterp,LocalYInterp,LocalZInterp);
    quiver3(XInterp,YInterp,ZInterp,...
        RValX(:,:,:,el),RValY(:,:,:,el),RValZ(:,:,:,el),'b');
end
title([FieldName ', ' FieldVariable]);
xlabel(['X - Axis ' '(' LengthUnit ')']);
ylabel(['Y - Axis ' '(' LengthUnit ')']);
zlabel(['Z - Axis ' '(' LengthUnit ')']);
pause;
close;